const requireDir = require('require-dir')
const path = require('path')
const fs = require('fs')
const blacklist = fs.readFileSync(path.join(__dirname, 'blacklist.txt'), 'utf8').split('\n')
const counts = require('download-counts')
const dependentCounts = require('dependent-counts')
const pluralize = require('pluralize')
const dedent = require('dedent')
const packages = Object.values(requireDir('./packages'))
  .filter(pkg => !blacklist.includes(pkg.name))
  .map(pkg => Object.assign(pkg, {averageDailyDownloads: counts[pkg.name] || 0}))
  .map(pkg => Object.assign(pkg, {
    dependentCounts: (dependentCounts.find(dep => dep.name === pkg.name) || {totalDirectDependents: 0})
  }))
  .sort((a, b) => b.averageDailyDownloads - a.averageDailyDownloads)

console.log(dedent`<!-- auto-generated by render.js -->

# Native Modules

> a list of ${packages.length} JavaScript modules with C++ addons

Find more datasets like this at 
[nice-registry/about](https://github.com/nice-registry/about#datasets).

## How?

This list is created by:

1. Consuming the entire npm registry using [package-stream](http://ghub.io/package-stream).
1. Plucking out packages that depend or devDepend on [nan](http://ghub.io/nan)
1. Sorting results by [average daily downloads](http://ghub.io/download-counts) and [direct dependents](http://ghub.io/dependent-counts) counts.


## Modules

`)

packages
.forEach((pkg, i) => {
  console.log(`${i+1}. [${pkg.name}](http://ghub.io/${pkg.name}) - ${pkg.description} (${pkg.averageDailyDownloads} ${pluralize('download', pkg.averageDailyDownloads)}/day; ${pkg.dependentCounts.totalDirectDependents} ${pluralize('direct dependent', pkg.dependentCounts.totalDirectDependents)})`)
})